export const alternatives = [
  {
    productName: 'Coca-Cola Classic 330ml',
    alternativeName: 'Sahara Cola 330ml',
    isExact: true,
    notes: 'بديل كولا محلي متوفر.',
    notesAr: 'بديل كولا محلي متوفر.',
  },
  {
    productName: 'Pepsi Cola 330ml',
    alternativeName: 'Sahara Cola 330ml',
    isExact: true,
    notes: 'بديل كولا محلي متوفر.',
    notesAr: 'بديل كولا محلي متوفر.',
  },
  {
    productName: 'Fanta Orange 330ml',
    alternativeName: 'Sahara Orange 330ml',
    isExact: true,
    notes: 'بديل مشروب برتقال محلي.',
    notesAr: 'بديل مشروب برتقال محلي.',
  },
  {
    productName: 'Lay\'s Classic Chips 170g',
    alternativeName: 'Al-Waha Potato Chips 150g',
    isExact: false,
    notes: 'بديل محلي للشيبس.',
    notesAr: 'بديل محلي للشيبس.',
  },
  {
    productName: 'KitKat 4 Finger',
    alternativeName: 'Al-Waha Chocolate Wafer 30g',
    isExact: true,
    notes: 'بديل ويفر محلي.',
    notesAr: 'بديل ويفر محلي.',
  },
  {
    productName: 'Oreo Original',
    alternativeName: 'Al-Waha Chocolate Wafer 30g',
    isExact: false,
    notes: 'بديل بسكويت محلي.',
    notesAr: 'بديل بسكويت محلي.',
  },
  {
    productName: 'Cadbury Dairy Milk 100g',
    alternativeName: 'Al-Waha Chocolate Wafer 30g',
    isExact: false,
    notes: 'بديل شوكولاتة محلي.',
    notesAr: 'بديل شوكولاتة محلي.',
  },
  {
    productName: 'Nescafe Classic 200g',
    alternativeName: 'Al-Waha Instant Coffee 100g',
    isExact: true,
    notes: 'بديل قهوة فورية محلي.',
    notesAr: 'بديل قهوة فورية محلي.',
  },
  {
    productName: 'Lipton Yellow Label Tea 100 bags',
    alternativeName: 'Al-Waha Black Tea 100 bags',
    isExact: true,
    notes: 'بديل شاي محلي.',
    notesAr: 'بديل شاي محلي.',
  },
  {
    productName: 'Nido Milk Powder 900g',
    alternativeName: 'Tripoli Milk 1L',
    isExact: false,
    notes: 'بديل ألبان محلي.',
    notesAr: 'بديل ألبان محلي.',
  },
  {
    productName: 'Ariel Detergent 3kg',
    alternativeName: 'Green Oasis Detergent 3kg',
    isExact: true,
    notes: 'بديل محلي للمنظفات.',
    notesAr: 'بديل محلي للمنظفات.',
  },
  {
    productName: 'Tide Detergent 3kg',
    alternativeName: 'Green Oasis Detergent 3kg',
    isExact: true,
    notes: 'بديل محلي للمنظفات.',
    notesAr: 'بديل محلي للمنظفات.',
  },
  {
    productName: 'Pantene Shampoo 400ml',
    alternativeName: 'Green Oasis Shampoo 400ml',
    isExact: false,
    notes: 'بديل محلي للعناية الشخصية.',
    notesAr: 'بديل محلي للعناية الشخصية.',
  },
  {
    productName: 'Dove Body Wash 500ml',
    alternativeName: 'Green Oasis Shampoo 400ml',
    isExact: false,
    notes: 'بديل محلي للعناية الشخصية.',
    notesAr: 'بديل محلي للعناية الشخصية.',
  },
  {
    productName: 'Starbucks House Blend 250g',
    alternativeName: 'Al-Waha Instant Coffee 100g',
    isExact: false,
    notes: 'بديل قهوة فورية محلي.',
    notesAr: 'بديل قهوة فورية محلي.',
  },
];
