export const companies = [
  {
    nameEn: 'The Coca-Cola Company',
    aliases: ['Coca Cola', 'Coke'],
    country: 'الولايات المتحدة',
    description: 'شركة مشروبات عالمية مدرجة ضمن قائمة المقاطعة.',
    descriptionAr: 'شركة مشروبات عالمية مدرجة ضمن قائمة المقاطعة.',
    verdictLabel: 'AVOID' as const,
  },
  {
    nameEn: 'PepsiCo',
    aliases: ['Pepsi'],
    country: 'الولايات المتحدة',
    description: 'شركة أغذية ومشروبات عالمية مدرجة ضمن المقاطعة.',
    descriptionAr: 'شركة أغذية ومشروبات عالمية مدرجة ضمن المقاطعة.',
    verdictLabel: 'AVOID' as const,
  },
  {
    nameEn: 'Nestle',
    aliases: ['Nestle', 'Nestle SA'],
    country: 'سويسرا',
    description: 'شركة أغذية ومشروبات عالمية مدرجة ضمن المقاطعة.',
    descriptionAr: 'شركة أغذية ومشروبات عالمية مدرجة ضمن المقاطعة.',
    verdictLabel: 'AVOID' as const,
  },
  {
    nameEn: 'Unilever',
    aliases: ['Unilever PLC'],
    country: 'المملكة المتحدة',
    description: 'شركة سلع استهلاكية عالمية مدرجة ضمن المقاطعة.',
    descriptionAr: 'شركة سلع استهلاكية عالمية مدرجة ضمن المقاطعة.',
    verdictLabel: 'AVOID' as const,
  },
  {
    nameEn: 'Procter & Gamble',
    aliases: ['P&G'],
    country: 'الولايات المتحدة',
    description: 'شركة منظفات وعناية شخصية مدرجة ضمن المقاطعة.',
    descriptionAr: 'شركة منظفات وعناية شخصية مدرجة ضمن المقاطعة.',
    verdictLabel: 'AVOID' as const,
  },
  {
    nameEn: 'Mondelez International',
    aliases: ['Mondelez'],
    country: 'الولايات المتحدة',
    description: 'شركة حلويات وسناكات عالمية مدرجة ضمن المقاطعة.',
    descriptionAr: 'شركة حلويات وسناكات عالمية مدرجة ضمن المقاطعة.',
    verdictLabel: 'AVOID' as const,
  },
  {
    nameEn: 'Starbucks Corporation',
    aliases: ['Starbucks'],
    country: 'الولايات المتحدة',
    description: 'سلسلة مقاهي عالمية مدرجة ضمن المقاطعة.',
    descriptionAr: 'سلسلة مقاهي عالمية مدرجة ضمن المقاطعة.',
    verdictLabel: 'AVOID' as const,
  },
  {
    nameEn: 'McDonald\'s Corporation',
    aliases: ['McDonalds'],
    country: 'الولايات المتحدة',
    description: 'سلسلة وجبات سريعة عالمية مدرجة ضمن المقاطعة.',
    descriptionAr: 'سلسلة وجبات سريعة عالمية مدرجة ضمن المقاطعة.',
    verdictLabel: 'AVOID' as const,
  },
  {
    nameEn: 'Sahara Beverages Co.',
    aliases: [],
    country: 'ليبيا',
    description: 'شركة محلية تقدم بدائل للمشروبات الغازية.',
    descriptionAr: 'شركة محلية تقدم بدائل للمشروبات الغازية.',
    verdictLabel: 'PREFERRED' as const,
  },
  {
    nameEn: 'Tripoli Dairy Co.',
    aliases: [],
    country: 'ليبيا',
    description: 'شركة ألبان محلية بمنتجات متوفرة في السوق الليبي.',
    descriptionAr: 'شركة ألبان محلية بمنتجات متوفرة في السوق الليبي.',
    verdictLabel: 'PREFERRED' as const,
  },
  {
    nameEn: 'Al-Waha Foods',
    aliases: [],
    country: 'ليبيا',
    description: 'شركة أغذية محلية تقدم بدائل سناكات وشاي وقهوة.',
    descriptionAr: 'شركة أغذية محلية تقدم بدائل سناكات وشاي وقهوة.',
    verdictLabel: 'PREFERRED' as const,
  },
  {
    nameEn: 'Green Oasis Detergents',
    aliases: [],
    country: 'ليبيا',
    description: 'شركة منظفات محلية تقدم بدائل للغسيل والعناية.',
    descriptionAr: 'شركة منظفات محلية تقدم بدائل للغسيل والعناية.',
    verdictLabel: 'PREFERRED' as const,
  },
];
