const boycottReason = 'منتج تابع لشركة مقاطعة.';
const alternativeReason = 'بديل محلي متوفر في السوق الليبي.';

export const products = [
  {
    nameEn: 'Coca-Cola Classic 330ml',
    nameAr: 'كوكا كولا كلاسيك 330مل',
    brandName: 'Coca-Cola',
    categoryName: 'مشروبات غازية',
    barcode: '5449000000996',
    verdictLabel: 'AVOID' as const,
    description: boycottReason,
    descriptionAr: boycottReason,
  },
  {
    nameEn: 'Fanta Orange 330ml',
    nameAr: 'فانتا برتقال 330مل',
    brandName: 'Fanta',
    categoryName: 'مشروبات غازية',
    barcode: '5449000011527',
    verdictLabel: 'AVOID' as const,
    description: boycottReason,
    descriptionAr: boycottReason,
  },
  {
    nameEn: 'Pepsi Cola 330ml',
    nameAr: 'بيبسي كولا 330مل',
    brandName: 'Pepsi',
    categoryName: 'مشروبات غازية',
    barcode: '012000001536',
    verdictLabel: 'AVOID' as const,
    description: boycottReason,
    descriptionAr: boycottReason,
  },
  {
    nameEn: 'Lay\'s Classic Chips 170g',
    nameAr: 'ليز شيبس كلاسيك 170غ',
    brandName: 'Lay\'s',
    categoryName: 'حلويات وسناكات',
    barcode: '028400064057',
    verdictLabel: 'AVOID' as const,
    description: boycottReason,
    descriptionAr: boycottReason,
  },
  {
    nameEn: 'KitKat 4 Finger',
    nameAr: 'كيت كات 4 أصابع',
    brandName: 'KitKat',
    categoryName: 'حلويات وسناكات',
    barcode: '5000112628265',
    verdictLabel: 'AVOID' as const,
    description: boycottReason,
    descriptionAr: boycottReason,
  },
  {
    nameEn: 'Nescafe Classic 200g',
    nameAr: 'نسكافيه كلاسيك 200غ',
    brandName: 'Nescafe',
    categoryName: 'قهوة وشاي',
    barcode: '7613036932875',
    verdictLabel: 'AVOID' as const,
    description: boycottReason,
    descriptionAr: boycottReason,
  },
  {
    nameEn: 'Nido Milk Powder 900g',
    nameAr: 'نيدو حليب بودرة 900غ',
    brandName: 'Nido',
    categoryName: 'ألبان',
    barcode: '7613033464058',
    verdictLabel: 'AVOID' as const,
    description: boycottReason,
    descriptionAr: boycottReason,
  },
  {
    nameEn: 'Lipton Yellow Label Tea 100 bags',
    nameAr: 'ليبتون شاي أصفر 100 كيس',
    brandName: 'Lipton',
    categoryName: 'قهوة وشاي',
    barcode: '5000108016052',
    verdictLabel: 'AVOID' as const,
    description: boycottReason,
    descriptionAr: boycottReason,
  },
  {
    nameEn: 'Ariel Detergent 3kg',
    nameAr: 'أريال مسحوق غسيل 3كغ',
    brandName: 'Ariel',
    categoryName: 'منظفات منزلية',
    barcode: '4084500168091',
    verdictLabel: 'AVOID' as const,
    description: boycottReason,
    descriptionAr: boycottReason,
  },
  {
    nameEn: 'Tide Detergent 3kg',
    nameAr: 'تايد مسحوق غسيل 3كغ',
    brandName: 'Tide',
    categoryName: 'منظفات منزلية',
    barcode: '037000389583',
    verdictLabel: 'AVOID' as const,
    description: boycottReason,
    descriptionAr: boycottReason,
  },
  {
    nameEn: 'Pantene Shampoo 400ml',
    nameAr: 'بانتين شامبو 400مل',
    brandName: 'Pantene',
    categoryName: 'عناية شخصية',
    barcode: '4084500396210',
    verdictLabel: 'AVOID' as const,
    description: boycottReason,
    descriptionAr: boycottReason,
  },
  {
    nameEn: 'Dove Body Wash 500ml',
    nameAr: 'دوف غسول جسم 500مل',
    brandName: 'Dove',
    categoryName: 'عناية شخصية',
    barcode: '8712561464200',
    verdictLabel: 'AVOID' as const,
    description: boycottReason,
    descriptionAr: boycottReason,
  },
  {
    nameEn: 'Oreo Original',
    nameAr: 'أوريو أصلي',
    brandName: 'Oreo',
    categoryName: 'حلويات وسناكات',
    barcode: '7622210100535',
    verdictLabel: 'AVOID' as const,
    description: boycottReason,
    descriptionAr: boycottReason,
  },
  {
    nameEn: 'Cadbury Dairy Milk 100g',
    nameAr: 'كادبوري ديري ميلك 100غ',
    brandName: 'Cadbury',
    categoryName: 'حلويات وسناكات',
    barcode: '7622210601698',
    verdictLabel: 'AVOID' as const,
    description: boycottReason,
    descriptionAr: boycottReason,
  },
  {
    nameEn: 'Starbucks House Blend 250g',
    nameAr: 'ستاربكس هاوس بليند 250غ',
    brandName: 'Starbucks',
    categoryName: 'قهوة وشاي',
    barcode: '7613035994713',
    verdictLabel: 'AVOID' as const,
    description: boycottReason,
    descriptionAr: boycottReason,
  },
  {
    nameEn: 'McDonald\'s Big Mac',
    nameAr: 'ماكدونالدز بيغ ماك',
    brandName: 'McDonald\'s',
    categoryName: 'وجبات سريعة',
    verdictLabel: 'AVOID' as const,
    description: boycottReason,
    descriptionAr: boycottReason,
  },

  // ===== ALTERNATIVES (PREFERRED) =====
  {
    nameEn: 'Sahara Cola 330ml',
    nameAr: 'ساهارا كولا 330مل',
    brandName: 'Sahara Cola',
    categoryName: 'مشروبات غازية',
    barcode: '6281000000101',
    verdictLabel: 'PREFERRED' as const,
    description: alternativeReason,
    descriptionAr: alternativeReason,
  },
  {
    nameEn: 'Sahara Orange 330ml',
    nameAr: 'ساهارا برتقال 330مل',
    brandName: 'Sahara Orange',
    categoryName: 'مشروبات غازية',
    barcode: '6281000000102',
    verdictLabel: 'PREFERRED' as const,
    description: alternativeReason,
    descriptionAr: alternativeReason,
  },
  {
    nameEn: 'Tripoli Milk 1L',
    nameAr: 'حليب طرابلس 1 لتر',
    brandName: 'Tripoli Milk',
    categoryName: 'ألبان',
    barcode: '6281000000201',
    verdictLabel: 'PREFERRED' as const,
    description: 'بديل محلي لمنتجات الألبان.',
    descriptionAr: 'بديل محلي لمنتجات الألبان.',
  },
  {
    nameEn: 'Al-Waha Chocolate Wafer 30g',
    nameAr: 'ويفر شوكولاتة الواحة 30غ',
    brandName: 'Al-Waha',
    categoryName: 'حلويات وسناكات',
    barcode: '6281000000301',
    verdictLabel: 'PREFERRED' as const,
    description: 'بديل محلي للحلويات والسناكات.',
    descriptionAr: 'بديل محلي للحلويات والسناكات.',
  },
  {
    nameEn: 'Al-Waha Potato Chips 150g',
    nameAr: 'شيبس الواحة 150غ',
    brandName: 'Al-Waha',
    categoryName: 'حلويات وسناكات',
    barcode: '6281000000302',
    verdictLabel: 'PREFERRED' as const,
    description: 'بديل محلي لمنتجات الشيبس.',
    descriptionAr: 'بديل محلي لمنتجات الشيبس.',
  },
  {
    nameEn: 'Al-Waha Black Tea 100 bags',
    nameAr: 'شاي الواحة 100 كيس',
    brandName: 'Al-Waha',
    categoryName: 'قهوة وشاي',
    barcode: '6281000000303',
    verdictLabel: 'PREFERRED' as const,
    description: 'بديل محلي للشاي.',
    descriptionAr: 'بديل محلي للشاي.',
  },
  {
    nameEn: 'Al-Waha Instant Coffee 100g',
    nameAr: 'قهوة فورية الواحة 100غ',
    brandName: 'Al-Waha',
    categoryName: 'قهوة وشاي',
    barcode: '6281000000304',
    verdictLabel: 'PREFERRED' as const,
    description: 'بديل محلي للقهوة سريعة التحضير.',
    descriptionAr: 'بديل محلي للقهوة سريعة التحضير.',
  },
  {
    nameEn: 'Green Oasis Detergent 3kg',
    nameAr: 'جرين أواسيس مسحوق غسيل 3كغ',
    brandName: 'Green Oasis',
    categoryName: 'منظفات منزلية',
    barcode: '6281000000401',
    verdictLabel: 'PREFERRED' as const,
    description: 'بديل محلي للمنظفات.',
    descriptionAr: 'بديل محلي للمنظفات.',
  },
  {
    nameEn: 'Green Oasis Shampoo 400ml',
    nameAr: 'جرين أواسيس شامبو 400مل',
    brandName: 'Green Oasis',
    categoryName: 'عناية شخصية',
    barcode: '6281000000402',
    verdictLabel: 'PREFERRED' as const,
    description: 'بديل محلي للعناية الشخصية.',
    descriptionAr: 'بديل محلي للعناية الشخصية.',
  },
];
