export const stores = [
  {
    name: 'سوق المدينة الجديدة',
    nameAr: 'سوق المدينة الجديدة',
    city: 'طرابلس',
    area: 'حي الأندلس',
    address: 'شارع السوق الرئيسي',
    addressAr: 'شارع السوق الرئيسي',
    tags: ['سوق'],
    isVerified: true,
  },
  {
    name: 'سوق بنغازي المركزي',
    nameAr: 'سوق بنغازي المركزي',
    city: 'بنغازي',
    area: 'وسط المدينة',
    address: 'شارع عمر المختار',
    addressAr: 'شارع عمر المختار',
    tags: ['سوق'],
    isVerified: true,
  },
  {
    name: 'سوق مصراتة المركزي',
    nameAr: 'سوق مصراتة المركزي',
    city: 'مصراتة',
    area: 'وسط المدينة',
    address: 'شارع طرابلس',
    addressAr: 'شارع طرابلس',
    tags: ['سوق'],
    isVerified: true,
  },
  {
    name: 'سوق سبها الشعبي',
    nameAr: 'سوق سبها الشعبي',
    city: 'سبها',
    area: 'حي المطار',
    address: 'الطريق الدائري',
    addressAr: 'الطريق الدائري',
    tags: ['سوق'],
    isVerified: true,
  },
  {
    name: 'سوق الزاوية الجديد',
    nameAr: 'سوق الزاوية الجديد',
    city: 'الزاوية',
    area: 'وسط المدينة',
    address: 'الطريق الرئيسي',
    addressAr: 'الطريق الرئيسي',
    tags: ['سوق'],
    isVerified: true,
  },
  {
    name: 'سوق البيضاء',
    nameAr: 'سوق البيضاء',
    city: 'البيضاء',
    area: 'شارع عمر المختار',
    address: 'شارع عمر المختار',
    addressAr: 'شارع عمر المختار',
    tags: ['سوق'],
    isVerified: true,
  },
];
